name: chinese_lunar_almanac
description: A pure Dart Chinese traditional almanac (Huangli) library with GanZhi, solar terms, flying stars, lunar mansions, and Yi/Ji.
version: 0.1.1
repository: https://github.com/RedSC1/chinese_lunar_almanac
topics:
  - chinese-calendar
  - lunar-calendar
  - almanac
  - fengshui

environment:
  sdk: ^3.10.8

# Add regular dependencies here.
dependencies:
  sxwnl_spa_dart: ^0.15.1
  # path: ^1.9.0

dev_dependencies:
  lints: ^6.0.0
  test: ^1.25.6
