// Generated by generate_day8char_things.py
// 日柱干支 → 额外宜忌 (FastBitSet.fromChunks)

import '../../utils/fast_bitset.dart';

/// 日柱干支的额外宜忌活动
///
/// 使用方式：遍历当日干支中的每个字，如果在表中则 merge 对应的宜忌。
/// 例如日柱「甲子」→ 匹配「甲」(忌开仓) 和「子」(宜沐浴)
class Day8CharThings {
  static const int _cap = 98;

  /// 天干规则: stemIndex(0~9) → (good, bad)
  /// 无规则的天干用 null 占位
  static final List<(FastBitSet, FastBitSet)?> stemRules = [
    (FastBitSet.fromChunks(_cap, [0x00000000, 0x00000000, 0x00000000, 0x00000000]), FastBitSet.fromChunks(_cap, [0x00000000, 0x00000001, 0x00000000, 0x00000000])), // 甲: 宜(无), 忌开仓
    (FastBitSet.fromChunks(_cap, [0x00000000, 0x00000000, 0x00000000, 0x00000000]), FastBitSet.fromChunks(_cap, [0x00000000, 0x00004000, 0x00000000, 0x00000000])), // 乙: 宜(无), 忌栽种
    null, // 丙: (无规则)
    (FastBitSet.fromChunks(_cap, [0x00000000, 0x00000000, 0x00000000, 0x00000000]), FastBitSet.fromChunks(_cap, [0x00040000, 0x00000800, 0x00000000, 0x00000000])), // 丁: 宜(无), 忌整容, 剃头
    null, // 戊: (无规则)
    null, // 己: (无规则)
    (FastBitSet.fromChunks(_cap, [0x00000000, 0x00000000, 0x00000000, 0x00000000]), FastBitSet.fromChunks(_cap, [0x00000000, 0x00000000, 0x00000040, 0x00000000])), // 庚: 宜(无), 忌经络
    (FastBitSet.fromChunks(_cap, [0x00000000, 0x00000000, 0x00000000, 0x00000000]), FastBitSet.fromChunks(_cap, [0x00000000, 0x00000000, 0x20000000, 0x00000000])), // 辛: 宜(无), 忌酝酿
    (FastBitSet.fromChunks(_cap, [0x00000000, 0x00000000, 0x00000000, 0x00000000]), FastBitSet.fromChunks(_cap, [0x00000000, 0x10000010, 0x00000000, 0x00000000])), // 壬: 宜(无), 忌开渠, 穿井
    null, // 癸: (无规则)
  ];

  /// 地支规则: branchIndex(0~11) → (good, bad)
  /// 无规则的地支用 null 占位
  static final List<(FastBitSet, FastBitSet)?> branchRules = [
    (FastBitSet.fromChunks(_cap, [0x00000000, 0x00040000, 0x00000000, 0x00000000]), FastBitSet.fromChunks(_cap, [0x00000000, 0x00000000, 0x00000000, 0x00000000])), // 子: 宜沐浴, 忌(无)
    (FastBitSet.fromChunks(_cap, [0x00000000, 0x00000000, 0x00000000, 0x00000000]), FastBitSet.fromChunks(_cap, [0x00004000, 0x00000000, 0x00000000, 0x00000000])), // 丑: 宜(无), 忌冠带
    (FastBitSet.fromChunks(_cap, [0x00000000, 0x00000000, 0x00000000, 0x00000000]), FastBitSet.fromChunks(_cap, [0x00000000, 0x04000000, 0x00000000, 0x00000000])), // 寅: 宜(无), 忌祭祀
    (FastBitSet.fromChunks(_cap, [0x00000000, 0x00000000, 0x00000000, 0x00000000]), FastBitSet.fromChunks(_cap, [0x00000000, 0x10000000, 0x00000000, 0x00000000])), // 卯: 宜(无), 忌穿井
    null, // 辰: (无规则)
    (FastBitSet.fromChunks(_cap, [0x00000000, 0x00000000, 0x00000000, 0x00000000]), FastBitSet.fromChunks(_cap, [0x00010000, 0x00000000, 0x00000000, 0x00000000])), // 巳: 宜(无), 忌出行
    (FastBitSet.fromChunks(_cap, [0x00000000, 0x00000000, 0x00000000, 0x00000000]), FastBitSet.fromChunks(_cap, [0x00000000, 0x00000000, 0x00000200, 0x00000000])), // 午: 宜(无), 忌苫盖
    (FastBitSet.fromChunks(_cap, [0x00000000, 0x00000000, 0x00000000, 0x00000000]), FastBitSet.fromChunks(_cap, [0x00000000, 0x00008000, 0x00000000, 0x00000000])), // 未: 宜(无), 忌求医疗病
    (FastBitSet.fromChunks(_cap, [0x00000000, 0x00000000, 0x00000000, 0x00000000]), FastBitSet.fromChunks(_cap, [0x00800000, 0x00000000, 0x00000000, 0x00000000])), // 申: 宜(无), 忌安床
    (FastBitSet.fromChunks(_cap, [0x00000000, 0x00000000, 0x00000000, 0x00000000]), FastBitSet.fromChunks(_cap, [0x10000000, 0x00000000, 0x00000000, 0x00000000])), // 酉: 宜(无), 忌宴会
    null, // 戌: (无规则)
    (FastBitSet.fromChunks(_cap, [0x00000000, 0x00040000, 0x00000000, 0x00000000]), FastBitSet.fromChunks(_cap, [0x00400000, 0x00000000, 0x00000000, 0x00000000])), // 亥: 宜沐浴, 忌嫁娶
  ];
}
